/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class PanelBienvenidaAdmin extends javax.swing.JPanel {

    /**
     * Creates new form PanelProductos
     */
    public PanelBienvenidaAdmin() {
        initComponents();
    }
    
    public JPanel getFondo() {
        return Panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        HeaderBienvenida = new javax.swing.JPanel();
        BienvenidaContainer = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(660, 580));

        Panel.setBackground(new java.awt.Color(255, 255, 255));
        Panel.setPreferredSize(new java.awt.Dimension(652, 578));
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Bienvenido");
        Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 109, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Elija una opcion:");
        Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 159, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Admin");
        Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 109, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("PRODUCTOS");
        Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 197, -1, 45));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("VENTAS");
        Panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 197, -1, 45));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("ESTADISTICAS");
        Panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 287, -1, 45));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("USUARIOS");
        Panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 287, -1, 45));

        HeaderBienvenida.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout HeaderBienvenidaLayout = new javax.swing.GroupLayout(HeaderBienvenida);
        HeaderBienvenida.setLayout(HeaderBienvenidaLayout);
        HeaderBienvenidaLayout.setHorizontalGroup(
            HeaderBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        HeaderBienvenidaLayout.setVerticalGroup(
            HeaderBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Panel.add(HeaderBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 652, -1));

        BienvenidaContainer.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout BienvenidaContainerLayout = new javax.swing.GroupLayout(BienvenidaContainer);
        BienvenidaContainer.setLayout(BienvenidaContainerLayout);
        BienvenidaContainerLayout.setHorizontalGroup(
            BienvenidaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        BienvenidaContainerLayout.setVerticalGroup(
            BienvenidaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        Panel.add(BienvenidaContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 650, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BienvenidaContainer;
    private javax.swing.JPanel HeaderBienvenida;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
