/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Clases.C_CRUDProductos;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class PanelProductos extends javax.swing.JPanel {

    /**
     * Creates new form PanelProductos
     */
    public PanelProductos() {
        initComponents();
        showPanel(P_view.getFondo());
    }
    private static PanelProductos instance;
    
    public void showPanel(JPanel p){
        p.setSize(660, 480);
        p.setLocation(0, 0);
        ProductosContainer.removeAll();
        ProductosContainer.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
        ProductosContainer.revalidate();
        ProductosContainer.repaint();
    }
    
    public final ProductosView P_view = new ProductosView();
    public final ProductosNew P_new = new ProductosNew();
    
      C_CRUDProductos objetoProductos = new C_CRUDProductos();
    
    public JPanel getFondo() {
        return Panel;
        
    }
    
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        HeaderProductos = new javax.swing.JPanel();
        BotonNew = new javax.swing.JButton();
        BotonView = new javax.swing.JButton();
        ProductosContainer = new javax.swing.JPanel();

        Panel.setBackground(new java.awt.Color(255, 255, 255));
        Panel.setPreferredSize(new java.awt.Dimension(650, 478));
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HeaderProductos.setBackground(new java.awt.Color(51, 51, 255));

        BotonNew.setBackground(new java.awt.Color(153, 204, 255));
        BotonNew.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        BotonNew.setText("Agregar producto");
        BotonNew.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 255, 255), null, new java.awt.Color(204, 255, 255)));
        BotonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNewActionPerformed(evt);
            }
        });

        BotonView.setBackground(new java.awt.Color(153, 204, 255));
        BotonView.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        BotonView.setText("Lista de productos");
        BotonView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 255, 255), null, new java.awt.Color(204, 255, 255)));
        BotonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderProductosLayout = new javax.swing.GroupLayout(HeaderProductos);
        HeaderProductos.setLayout(HeaderProductosLayout);
        HeaderProductosLayout.setHorizontalGroup(
            HeaderProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderProductosLayout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(BotonView, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonNew, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        HeaderProductosLayout.setVerticalGroup(
            HeaderProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderProductosLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(HeaderProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonNew, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonView, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        Panel.add(HeaderProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, -1));

        ProductosContainer.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ProductosContainerLayout = new javax.swing.GroupLayout(ProductosContainer);
        ProductosContainer.setLayout(ProductosContainerLayout);
        ProductosContainerLayout.setHorizontalGroup(
            ProductosContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        ProductosContainerLayout.setVerticalGroup(
            ProductosContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        Panel.add(ProductosContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 660, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNewActionPerformed
        showPanel(P_new);
    }//GEN-LAST:event_BotonNewActionPerformed

    private void BotonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonViewActionPerformed
        P_view.actualizarProductos();
        showPanel(P_view);
    }//GEN-LAST:event_BotonViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonNew;
    private javax.swing.JButton BotonView;
    private javax.swing.JPanel HeaderProductos;
    private javax.swing.JPanel Panel;
    private javax.swing.JPanel ProductosContainer;
    // End of variables declaration//GEN-END:variables
}
