/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import javax.swing.JPanel;


/**
 *
 * @author User
 */
public class ProductosNew extends javax.swing.JPanel {

    /**
     * Creates new form ProductosNew
     */
    public ProductosNew() {
        initComponents();
    }
    
    public JPanel getFondo() {
        return Panel;
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Precio = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        cancelarBoton = new javax.swing.JButton();
        aceptarBoton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(660, 480));

        Panel.setBackground(new java.awt.Color(255, 255, 255));
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Ingresar nuevo producto");
        Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Precio ($):");
        Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 274, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Nombre de producto:");
        Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 127, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("____________________________________________________________________");
        Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 189, -1, -1));
        Panel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 220, 499, 10));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("____________________________");
        Panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 317, 216, -1));
        Panel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 348, 205, 10));

        Precio.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        Precio.setBorder(null);
        Precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioActionPerformed(evt);
            }
        });
        Panel.add(Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 210, -1));

        Nombre.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        Nombre.setBorder(null);
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        Panel.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 510, -1));

        cancelarBoton.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        cancelarBoton.setText("Cancelar");
        cancelarBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cancelarBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBotonActionPerformed(evt);
            }
        });
        Panel.add(cancelarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, -1, -1));

        aceptarBoton.setBackground(new java.awt.Color(102, 102, 255));
        aceptarBoton.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        aceptarBoton.setForeground(new java.awt.Color(255, 255, 255));
        aceptarBoton.setText("Aceptar");
        aceptarBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        aceptarBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aceptarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBotonActionPerformed(evt);
            }
        });
        Panel.add(aceptarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void cancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBotonActionPerformed
            Precio.setText("");
            Nombre.setText("");
            
            
    }//GEN-LAST:event_cancelarBotonActionPerformed

    private void aceptarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBotonActionPerformed
            
            Precio.setText("");
            Nombre.setText("");
    }//GEN-LAST:event_aceptarBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nombre;
    private javax.swing.JPanel Panel;
    private javax.swing.JTextField Precio;
    private javax.swing.JButton aceptarBoton;
    private javax.swing.JButton cancelarBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
