/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class PanelVentas extends javax.swing.JPanel {

    /**
     * Creates new form PanelProductos
     */
    public PanelVentas() {
        initComponents();
        showPanel(V_view);
        V_view.actualizarProductos();
    }
    
    public void showPanel(JPanel p){
        p.setSize(660, 480);
        p.setLocation(0, 0);
        VentasContainer.removeAll();
        VentasContainer.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
        VentasContainer.revalidate();
        VentasContainer.repaint();
    }
    
    public final VentasView V_view = new VentasView();
    public final VentasNew V_new = new VentasNew();
    
    
    public JPanel getFondo() {
        return Panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        HeaderVentas = new javax.swing.JPanel();
        BotonView = new javax.swing.JButton();
        BotonNew = new javax.swing.JButton();
        VentasContainer = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(660, 580));

        Panel.setBackground(new java.awt.Color(255, 255, 255));
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HeaderVentas.setBackground(new java.awt.Color(4, 124, 36));

        BotonView.setBackground(new java.awt.Color(5, 171, 45));
        BotonView.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        BotonView.setText("Historial de Ventas");
        BotonView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 255, 255), null, new java.awt.Color(204, 255, 255)));
        BotonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonViewActionPerformed(evt);
            }
        });

        BotonNew.setBackground(new java.awt.Color(5, 171, 45));
        BotonNew.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        BotonNew.setText("Agregar Venta");
        BotonNew.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 255, 255), null, new java.awt.Color(204, 255, 255)));
        BotonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderVentasLayout = new javax.swing.GroupLayout(HeaderVentas);
        HeaderVentas.setLayout(HeaderVentasLayout);
        HeaderVentasLayout.setHorizontalGroup(
            HeaderVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderVentasLayout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(BotonView, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonNew, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        HeaderVentasLayout.setVerticalGroup(
            HeaderVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderVentasLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(HeaderVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonNew, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonView, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        Panel.add(HeaderVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, -1));

        VentasContainer.setBackground(new java.awt.Color(249, 246, 242));

        javax.swing.GroupLayout VentasContainerLayout = new javax.swing.GroupLayout(VentasContainer);
        VentasContainer.setLayout(VentasContainerLayout);
        VentasContainerLayout.setHorizontalGroup(
            VentasContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        VentasContainerLayout.setVerticalGroup(
            VentasContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        Panel.add(VentasContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 660, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonViewActionPerformed
        V_view.actualizarProductos();
        showPanel(V_view);
    }//GEN-LAST:event_BotonViewActionPerformed

    private void BotonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNewActionPerformed
        showPanel(V_new);
    }//GEN-LAST:event_BotonNewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonNew;
    private javax.swing.JButton BotonView;
    private javax.swing.JPanel HeaderVentas;
    private javax.swing.JPanel Panel;
    private javax.swing.JPanel VentasContainer;
    // End of variables declaration//GEN-END:variables
}
