/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import javax.swing.JPanel;

/**
 *
 * @author User
 */
public final class PanelAdmin extends javax.swing.JFrame {

    /**
     * Creates new form PanelAdmin
     */
    public PanelAdmin() {
        initComponents();
        showPanel(P_inicio.getFondo());
    }
    
    private final PanelProductos Pproductos = new PanelProductos();
    private final PanelUsuarios Pusuarios = new PanelUsuarios();
    private final PanelVentas Pventas = new PanelVentas();
    private final PanelBienvenidaAdmin P_inicio = new PanelBienvenidaAdmin();
    
    public void showPanel(JPanel p){
        p.setSize(650, 580);
        p.setLocation(0, 0);
        PanelContainer.removeAll();
        PanelContainer.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
        PanelContainer.revalidate();
        PanelContainer.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminContainer = new javax.swing.JPanel();
        PanelContainer = new javax.swing.JPanel();
        SliderAdmin = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        botonInicio = new javax.swing.JMenu();
        Gestionar = new javax.swing.JMenu();
        botonProductos = new javax.swing.JMenuItem();
        botonVentas = new javax.swing.JMenuItem();
        botonUsuarios = new javax.swing.JMenuItem();
        Estadistica = new javax.swing.JMenu();
        CerrarSesion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdminContainer.setBackground(new java.awt.Color(255, 255, 255));
        AdminContainer.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                AdminContainerComponentHidden(evt);
            }
        });
        AdminContainer.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                AdminContainerPropertyChange(evt);
            }
        });
        AdminContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelContainer.setBackground(new java.awt.Color(249, 246, 242));
        PanelContainer.setPreferredSize(new java.awt.Dimension(650, 478));

        javax.swing.GroupLayout PanelContainerLayout = new javax.swing.GroupLayout(PanelContainer);
        PanelContainer.setLayout(PanelContainerLayout);
        PanelContainerLayout.setHorizontalGroup(
            PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        PanelContainerLayout.setVerticalGroup(
            PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        AdminContainer.add(PanelContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 660, 580));

        SliderAdmin.setBackground(new java.awt.Color(0, 26, 41));
        SliderAdmin.setPreferredSize(new java.awt.Dimension(150, 578));

        javax.swing.GroupLayout SliderAdminLayout = new javax.swing.GroupLayout(SliderAdmin);
        SliderAdmin.setLayout(SliderAdminLayout);
        SliderAdminLayout.setHorizontalGroup(
            SliderAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        SliderAdminLayout.setVerticalGroup(
            SliderAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        AdminContainer.add(SliderAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 578));

        botonInicio.setText("Inicio");
        botonInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonInicioMouseClicked(evt);
            }
        });
        jMenuBar1.add(botonInicio);

        Gestionar.setText("Gestionar");

        botonProductos.setText("Productos");
        botonProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProductosActionPerformed(evt);
            }
        });
        Gestionar.add(botonProductos);

        botonVentas.setText("Ventas");
        botonVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVentasActionPerformed(evt);
            }
        });
        Gestionar.add(botonVentas);

        botonUsuarios.setText("Usuarios");
        botonUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUsuariosActionPerformed(evt);
            }
        });
        Gestionar.add(botonUsuarios);

        jMenuBar1.add(Gestionar);

        Estadistica.setText("Estadistica");
        jMenuBar1.add(Estadistica);

        CerrarSesion.setText("Cerrar sesion");
        CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarSesionMouseClicked(evt);
            }
        });
        jMenuBar1.add(CerrarSesion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AdminContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProductosActionPerformed
            showPanel(Pproductos.getFondo());
    }//GEN-LAST:event_botonProductosActionPerformed

    private void AdminContainerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_AdminContainerPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminContainerPropertyChange

    private void AdminContainerComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_AdminContainerComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminContainerComponentHidden

    private void botonVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVentasActionPerformed
        showPanel(Pventas.getFondo());
    }//GEN-LAST:event_botonVentasActionPerformed

    private void botonUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUsuariosActionPerformed
        showPanel(Pusuarios.getFondo());
    }//GEN-LAST:event_botonUsuariosActionPerformed

    private void botonInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMouseClicked
        showPanel(P_inicio.getFondo());
    }//GEN-LAST:event_botonInicioMouseClicked

    private void CerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesionMouseClicked
        this.setVisible(false);
        FormLogin objetoLogin = new FormLogin();
        objetoLogin.setVisible(true);
    }//GEN-LAST:event_CerrarSesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminContainer;
    private javax.swing.JMenu CerrarSesion;
    private javax.swing.JMenu Estadistica;
    private javax.swing.JMenu Gestionar;
    private javax.swing.JPanel PanelContainer;
    private javax.swing.JPanel SliderAdmin;
    private javax.swing.JMenu botonInicio;
    private javax.swing.JMenuItem botonProductos;
    private javax.swing.JMenuItem botonUsuarios;
    private javax.swing.JMenuItem botonVentas;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

}