/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Clases.C_CRUDVentas;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Moises
 */
public class VentasView extends javax.swing.JPanel {

    /**
     * Creates new form VentasView
     */
    public VentasView() {
        initComponents();
    }

    C_CRUDVentas objetoVentas = new C_CRUDVentas();
    
    
    public void actualizarProductos(){
        objetoVentas.MostrarVentas(registros);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        registrosContainer = new javax.swing.JScrollPane();
        registros = new javax.swing.JTable();
        botonEliminar = new javax.swing.JButton();
        botonDetalles = new javax.swing.JButton();
        botonModificar1 = new javax.swing.JButton();

        jPanel1.setPreferredSize(new java.awt.Dimension(660, 480));

        Panel.setBackground(new java.awt.Color(249, 246, 242));
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("MS UI Gothic", 0, 30)); // NOI18N
        jLabel2.setText("Ventas");
        Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        registros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        registrosContainer.setViewportView(registros);

        Panel.add(registrosContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        botonEliminar.setBackground(new java.awt.Color(100, 168, 160));
        botonEliminar.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        Panel.add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 120, 40));

        botonDetalles.setBackground(new java.awt.Color(100, 168, 160));
        botonDetalles.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        botonDetalles.setText("Detalles");
        botonDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDetallesActionPerformed(evt);
            }
        });
        Panel.add(botonDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 120, 40));

        botonModificar1.setBackground(new java.awt.Color(100, 168, 160));
        botonModificar1.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        botonModificar1.setText("Modificar");
        botonModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificar1ActionPerformed(evt);
            }
        });
        Panel.add(botonModificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 120, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        try {
            int confirmar =  JOptionPane.showConfirmDialog(null, "Estas seguro de Eliminar?");
            if(confirmar == 0){
                objetoVentas.EliminarVenta(registros);
                objetoVentas.MostrarVentas(registros);
            }else{
                System.out.println("Ok, no eliminamo pa");
            }

        } catch (SQLException ex) {
            Logger.getLogger(ProductosView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDetallesActionPerformed
        VentasDetalles1 pantalla = new VentasDetalles1();
        pantalla.setVisible(true);
    }//GEN-LAST:event_botonDetallesActionPerformed

    private void botonModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonModificar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton botonDetalles;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonModificar1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable registros;
    private javax.swing.JScrollPane registrosContainer;
    // End of variables declaration//GEN-END:variables
}
