/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Clases.C_CRUDVentas;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Moises
 */
public class VentasNew extends javax.swing.JPanel {

    /**
     * Creates new form VentasNew
     */
    public VentasNew() {
        initComponents();
        modeloPedido.addColumn("Producto");
        modeloPedido.addColumn("Costo");
        modeloPedido.addColumn("Cantidad");
        modeloPedido.addColumn("total");
        objetoVentas.RellenarComboBox("productos", "nombre_producto", boxproducto);
    }
    
    C_CRUDVentas objetoVentas = new C_CRUDVentas();
    DefaultTableModel modeloPedido = new DefaultTableModel();
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cancelarBoton = new javax.swing.JButton();
        aceptarBoton = new javax.swing.JButton();
        fechaVenta = new com.toedter.calendar.JDateChooser();
        boxproducto = new javax.swing.JComboBox<>();
        ingresar = new javax.swing.JButton();
        cantidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaventa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        botonModificar2 = new javax.swing.JButton();
        botonEliminar2 = new javax.swing.JButton();

        jPanel1.setPreferredSize(new java.awt.Dimension(660, 480));

        Panel.setBackground(new java.awt.Color(249, 246, 242));
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Registrar nueva venta");
        Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Fecha de venta");
        Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        Panel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 320, 10));

        cancelarBoton.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        cancelarBoton.setText("Cancelar");
        cancelarBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cancelarBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBotonActionPerformed(evt);
            }
        });
        Panel.add(cancelarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, -1, -1));

        aceptarBoton.setBackground(new java.awt.Color(5, 171, 45));
        aceptarBoton.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        aceptarBoton.setForeground(new java.awt.Color(255, 255, 255));
        aceptarBoton.setText("Aceptar");
        aceptarBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        aceptarBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aceptarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBotonActionPerformed(evt);
            }
        });
        Panel.add(aceptarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 420, 90, -1));

        fechaVenta.setDateFormatString("yyyy-MM-dd");
        Panel.add(fechaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 170, -1));

        boxproducto.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        Panel.add(boxproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        ingresar.setText("Ingresar");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });
        Panel.add(ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        cantidad.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        cantidad.setToolTipText("");
        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });
        cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidadKeyTyped(evt);
            }
        });
        Panel.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 80, 20));

        tablaventa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Costo", "Cantidad", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaventa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaventaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tablaventaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tablaventa);

        Panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 330, 180));

        jLabel1.setText("Producto:");
        Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel3.setText("Cantidad:");
        Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        total.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        total.setText("Total: 0$");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalKeyTyped(evt);
            }
        });
        Panel.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 100, -1));

        botonModificar2.setBackground(new java.awt.Color(100, 168, 160));
        botonModificar2.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        botonModificar2.setText("Modificar");
        botonModificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificar2ActionPerformed(evt);
            }
        });
        Panel.add(botonModificar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 100, 30));

        botonEliminar2.setBackground(new java.awt.Color(100, 168, 160));
        botonEliminar2.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        botonEliminar2.setText("Eliminar");
        botonEliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminar2ActionPerformed(evt);
            }
        });
        Panel.add(botonEliminar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 100, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBotonActionPerformed

    }//GEN-LAST:event_cancelarBotonActionPerformed

    private void aceptarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBotonActionPerformed
        objetoVentas.InsertarVenta(fechaVenta,tablaventa);
        JOptionPane.showMessageDialog(null,"Venta registrada Correctamente");
    }//GEN-LAST:event_aceptarBotonActionPerformed

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadActionPerformed

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        String producto = boxproducto.getSelectedItem().toString();
        int canti = Integer.parseInt(cantidad.getText());
        objetoVentas.RellenarTablaVenta(modeloPedido,tablaventa, producto, canti);
        
        System.out.println(objetoVentas.CalcularTotal(tablaventa));
        total.setText(objetoVentas.CalcularTotal(tablaventa));
    }//GEN-LAST:event_ingresarActionPerformed

    private void cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyTyped
        int key = evt.getKeyChar();
        boolean numero = key >= 48 && key <= 57;
        if(!numero){
            evt.consume();
        }
        if(cantidad.getText().trim().length() >= 10){
            evt.consume();
        }
    }//GEN-LAST:event_cantidadKeyTyped

    private void totalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalKeyTyped
        evt.consume();
    }//GEN-LAST:event_totalKeyTyped

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void botonModificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificar2ActionPerformed

            int confirmar =  JOptionPane.showConfirmDialog(null, "Estas seguro de Modificar?");
            if(confirmar == 0){
                objetoVentas.ModificarVenta2(tablaventa);
                total.setText(objetoVentas.CalcularTotal(tablaventa));
                JOptionPane.showMessageDialog(null,"Modificacion exitosa");
            }else{
                System.out.println("Ok, no modificamos pa");
            }
    }//GEN-LAST:event_botonModificar2ActionPerformed

    private void botonEliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminar2ActionPerformed

                objetoVentas.EliminarVenta2(tablaventa);
    }//GEN-LAST:event_botonEliminar2ActionPerformed

    private void tablaventaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaventaKeyTyped
        int row = tablaventa.getSelectedRow();
        int column = tablaventa.getSelectedColumn();
        
        boolean editable = tablaventa.isCellEditable(row, column);
        if(!editable){
            evt.consume();
        }
    }//GEN-LAST:event_tablaventaKeyTyped

    private void tablaventaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaventaKeyPressed
        int row = tablaventa.getSelectedRow();
        int column = tablaventa.getSelectedColumn();
        
        boolean editable = tablaventa.isCellEditable(row, column);
        if(!editable){
            evt.consume();
        }
    }//GEN-LAST:event_tablaventaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton aceptarBoton;
    private javax.swing.JButton botonEliminar2;
    private javax.swing.JButton botonModificar2;
    private javax.swing.JComboBox<String> boxproducto;
    private javax.swing.JButton cancelarBoton;
    private javax.swing.JTextField cantidad;
    private com.toedter.calendar.JDateChooser fechaVenta;
    private javax.swing.JButton ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablaventa;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
